version: "3"

services:
  redis:
    image: "redis:alpine"
    restart: always
    volumes:
      - "redis:/data"

  mobile_build_scheduler:
    build: .
    restart: always
    ports:
      - "3000:80"
    environment:
      - PORT=80
      - REDIS_HOST=redis
      - FIRE_HOUR=${FIRE_HOUR:-18}
      - FIRE_MINUTE=${FIRE_MINUTE:-0}
      - FIRE_SECOND=${FIRE_SECOND:-0}
      - HOST_IP=${HOST_IP}
      - HOST_SSH_PORT=${HOST_SSH_PORT:-22}
      - ID_RSA=${ID_RSA}
      - ID_RSA_PUB=${ID_RSA_PUB}
      - HOST_WORKDIR=${HOST_WORKDIR}
      - HOST_USER=${HOST_USER}
    depends_on:
      - redis

volumes:
  redis:
    external: true
